---
title: "Analysis with monocle"
output: html_notebook
---


```{r}
library(monocle)
library(data.table)
library(ggplot2)
```

```{r}
data <- read.delim("monocle/only_genes_CD4tcells_tpm.txt", check.names = F, row.names = 1)
sampleInfo <- read.delim("monocle/CD4tcells_sample_day_info.txt", check.names = F, row.names = 1)
geneInfo   <- fread("/nfs/research2/teichmann/reference/mus-musculus/ensembl85-mouse-tx-annotation.csv")
geneInfo   <- subset(geneInfo, select=c("Ensembl Gene ID",
                                        "Associated Gene Name",
                                        "Gene type"))
geneInfo   <- unique(geneInfo)
```

```{r}
tmp <- data.frame(genes = rownames(data), seq = 1:nrow(data))
geneInfo <- merge(geneInfo, tmp , by.x="Ensembl Gene ID", by.y="genes", all.y=T)
geneInfo <- geneInfo[order(geneInfo$seq),]
geneInfo$seq <- NULL
geneInfo <- as.data.frame(geneInfo)
rownames(geneInfo) <- geneInfo$`Ensembl Gene ID`
```

```{r}
mycolors <- c("#81CDC3", "#EB867F",  "#D0AB80", "#BDD68F", "#F9EF76")
names(mycolors) <- c("day_0", "day_2", "day_3", "day_4", "day_7")

colScale <- scale_colour_manual(name = "days", values = mycolors)
```


```{r}
pd <- new("AnnotatedDataFrame", data = sampleInfo)
fd <- new("AnnotatedDataFrame", data = geneInfo)
cell_data <- newCellDataSet(as(as.matrix(data), "sparseMatrix"),
                            phenoData = pd,
                            featureData = fd,
                            lowerDetectionLimit=1, 
                            expressionFamily = tobit())
```


```{r}
cell_data <- estimateSizeFactors(cell_data)
# cell_data <- estimateDispersions(cell_data)

```


```{r}
cell_data <- detectGenes(cell_data, min_expr = 0.1)
print(head(fData(cell_data)))
```

```{r}
expressed_genes <- row.names(subset(fData(cell_data), num_cells_expressed >= 50))
```

```{r}
print(head(pData(cell_data)))
```

```{r}
pData(cell_data)$Total_mRNAs <- Matrix::colSums(exprs(cell_data))
```

```{r}
cell_data <- detectGenes(cell_data, min_expr = 0.1)
```


### log-transform expression values

```{r}
L <- log(exprs(cell_data[expressed_genes,]))
```


```{r}
# Standardize each gene, so that they are all on the same scale,
# Then melt the data with plyr so we can plot it easily"
melted_dens_df <- melt(Matrix::t(scale(Matrix::t(L))))
```

```{r}
# Plot the distribution of the standardized gene expression values.
qplot(value, geom="density", data=melted_dens_df) + stat_function(fun = dnorm, size=0.5, color="red") +
xlab("Standardized log(FPKM)") +
ylab("Density")

```


```{r}
diff_test_res <- differentialGeneTest(cell_data[expressed_genes,],
                                      fullModelFormulaStr="~GroupID")
```

```{r}
sig_genes <- subset(diff_test_res, qval < 0.1)number of
head(sig_genes[order(sig_genes$qval),], n=20)
```

# ordering cells by progress

```{r}
ordering_genes <- row.names(subset(diff_test_res, qval < 0.01))
ordering_genes <- intersect(ordering_genes, expressed_genes)
```

```{r}
cell_data <- setOrderingFilter(cell_data, ordering_genes)
```

```{r}
cell_data <- reduceDimension(cell_data, max_components=2)
```

```{r}
cell_data <- orderCells(cell_data, reverse=FALSE)
```


```{r}
plot_cell_trajectory(cell_data, color_by="GroupID") +
  colScale
```

```{r}
plot_cell_trajectory(cell_data, color_by="State")
```